### ISSUE TITLE
🔷 [Epic] Integrate RoC Engine into Near.org 

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1061]
## What ?

**High Level Goal:**

Support the march towards a production release of the [RoC Engine ](https://github.com/near/bos-web-engine) by completing the integration points that we expect gateway operators and dapp developers to experience, such that we find & fix any issues and document our findings as recommended practices. 

## Why ?

**We expect our target users to experience several scenarios:**
 
- As a gateway operator, how do I transition from near-social-vm to RoC?
- As a gateway operator, how do simultaneously support both near-social-vm and RoC?
- As a dapp developer, how should I determine if a gateway supports the engine that my app requires? 

**Move the Needle:**
The KRs which this epic should affect
  1. The number of BOS Gateways which support the RoCEngine is at least 2
  2. Three of the most popular BOS gateways have published their plans to deprecate support for near-social-vm
---

**Go To Market Needs**
- a near.org/blog post that highlights the benefits of RoC, and our recommended adoption practices for gateway operators and dapp developers 

```[tasklist]
### Tasks
- [ ] https://github.com/near/near-discovery/issues/1130
- [ ] https://github.com/near/near-discovery/issues/1131
- [ ] https://github.com/near/near-discovery/issues/1132
```
