### ISSUE TITLE
migrate `blog` content from `pages.near.org`

### ISSUE THREAD

**Issue by thisisjoshford** [near/near-discovery#1100]
Once our new `blog` posts are shipped we should migrate all old content from `pages.near.org`; ideally with a script that does this work programmatically. :) 

```[tasklist]
### Tasks
- [x] Ensure migration retains original content copy, assets, and authors
- [x] Create URL redirects from `pages.near.org` to new content
- [x] Deprecate `pages.near.org`
```
