### ISSUE TITLE
Button up Logged-in Design Tasks

### ISSUE THREAD

**Issue by vanessadespain** [near/near-discovery#1145]
Finish up the remaining design tasks to be able to set down the logged-in experience. 

We had made updates to the logged-in navigation and homepage to improve the experience. I'm doing one more push to improve the CTAs on the homepage and add link-out icons to items in the new navigation that open in a new tab. 

Also helping to audit the current Near.org for Create Account CTAs in the content. [Audit here](https://docs.google.com/spreadsheets/d/1i0pGRIIMAXdZL1sIM4mT0_WN9htbCQ-FhhrjwGZshys/edit#gid=0)

[Figma](https://www.figma.com/file/nqgzMvVASTSHVqUQPFQWsV/WORKING-%2F-Q1-'24-%2F-Website---v3.2024?type=design&node-id=902-21673&mode=design)
```[tasklist]
### Tasks
- [x] Add link-out icons to navigation in the logged-in navigation
- [x] Audit the "Create Account" CTAs on Near.org
- [x] Change the logged-out home page to match the logged-in home page content. (instead of current near.org marketing page)
```

**Comment by vanessadespain** [comment]
When i'm logged out of the experience, the navigation should include Sign-in and Create Account buttons: 
<img width="1000" alt="image" src="https://github.com/near/near-discovery/assets/8346374/c529f369-bf75-4ad9-866f-d3e446b64126">

**Comment by vanessadespain** [comment]
[Gateway CTA Audit is here](https://docs.google.com/spreadsheets/d/1i0pGRIIMAXdZL1sIM4mT0_WN9htbCQ-FhhrjwGZshys/edit#gid=0)

**Comment by vanessadespain** [comment]
[Figma Link](https://www.figma.com/file/nqgzMvVASTSHVqUQPFQWsV/WORKING-%2F-Q1-'24-%2F-Website---v3.2024?type=design&node-id=788%3A10697&mode=design&t=zYrE9kuhqhQU60oc-1)

Add in link-out icons (ArrowSquareOut on Phosphor) to items in the menu that will open in new tab: 
![image](https://github.com/near/near-discovery/assets/8346374/12d51254-b48d-4826-ab54-0f354ae01b7e)
![image](https://github.com/near/near-discovery/assets/8346374/c0fd5141-46da-4003-9c1d-fe72b8945181)

**Comment by shelegdmitriy** [comment]
If I recall this correctly, this task is about this things:
  1. Add icon to menu items which points to be opened in the new window (such as _Documentation_, _Careers_, _Docs_, _GitHub_);
  2. Make this view for logged in users to be also accessible for a logged out users
  
Am I right?

@charleslavon @vanessadespain ?

**Comment by vanessadespain** [comment]
Thanks for the questions @shelegdmitriy let me know if the following doesn't make sense or needs further clarification. 

1. Yes, you got it! Design for this is [here](https://www.figma.com/file/nqgzMvVASTSHVqUQPFQWsV/WORKING-%2F-Q1-'24-%2F-Website---v3.2024?type=design&node-id=788%3A10697&mode=design&t=Q7MjmsyrhfxSaVt3-1)
2. That's correct, since this destination will be separated from Near.org we don't want to rely on the Near.org homepage being nested in dev.near.org for logged-out users. 
3. Charles decided to no longer make this change. We'll leave the copy as it in production currently. 
4. Adding a logged out state with Sign in/Create account buttons so that a user can arrive here and be able to access their account. This is so that again we're not relying on Near.org to prompt log-in. 

@charleslavon please correct me if i'm wrong.

**Comment by shelegdmitriy** [comment]
Thank you @vanessadespain !

**Comment by charleslavon** [comment]
Regarding `2` It looks like this is already the UX for logged out users.- https://dev.near.org/?sidebar=true

**Comment by charleslavon** [comment]
@shelegdmitriy also this task includes updating the call-to-action links as documented [here](https://docs.google.com/spreadsheets/d/1i0pGRIIMAXdZL1sIM4mT0_WN9htbCQ-FhhrjwGZshys/edit#gid=0)

**Comment by charleslavon** [comment]
@shelegdmitriy  Also to clarify, this work should include making the UX that appears with `?sidebar=true` the default experience for dev.near.org, without affecting the current near.org.

**Comment by vanessadespain** [comment]
+1 to Charles' clarification. The logged-out navigation already exists, but we just want to update home page when logged out to show OUR new gateway homepage rather than the near.org marketing homepage. 
@shelegdmitriy

**Comment by shelegdmitriy** [comment]
@charleslavon thanks for the clarification, I got it!

**Comment by shelegdmitriy** [comment]
Hey @vanessadespain. FYI: this changes are live on https://dev.near.org
