### ISSUE TITLE
🔷 [Epic] Near Event Ticketing UX

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#1165]
- **High Level Goal:**

Create a UX leveraging Near technologies ( Accounts, KeyPom, Wallet-selector, NFTs, etc)  to issue tickets for in-person event series, aiming to solve 4 issues with existing ticketing platforms: 

1. they are cost prohibitive (especially for larger events)
2. they maintain custody of the proceeds from ticket sales and delay paying event producers until a week after an event occurs
3. they lack of feature parity across mobile platforms
4. They do not provide a simple way to deploy a white labeled ticketing platform personalized to an event producer’s brand.

[User Stories & Product Hypothesis](https://docs.google.com/document/d/1DsZfDVh8yrkHr3HPGcQk4lawDFlNacnjoGDzh7md1fQ/edit)
[Keypom's implementation ](https://github.com/keypom/event-pass)

---
 **MVP Goals**

- Demonstrate use cases which solve real world problems, where we can get at least 10s of users to participate in user interviews during development and MVP usage during a Beta Release
- Build the MVP along with a well-documented boilerplate template that would enable developers to quickly launch and customize their own ticketing system. or cross-chain asset management tool that already has the wallet, mpc contract, and user onboarding flows implemented.
- Deliver an MVP for Alpha (internal) usage testing within 6-weeks
- Deliver a release to Beta users within 2-weeks post Alpha

**Potential Goals Beyond the MVP**
- Showcase Chain Abstraction via Cross Chain management of NFTs or FTs with v2.multichain-mpc.testnet, wallet-selector, and keypom’s event & ticketing flows.

**This epic includes two deliverables.** 
1. A minimally branded, mobile-optimized consumer app that enables event producers to create events and setup tickets; with a corresponding UI that is user focused that enables ticket purchasing and scanning to validate a ticket.. 
5. A Boilerplate template application, similar to this [Loyalty Program Template](https://github.com/near/boilerplate-template-loyalty-program-with-ft), that allows developers to quickly customize and deploy their own event ticketing program.

**Things we'll want** 
1. 90% coverage by unit tests for each functional flow
2. Devs/Docs people who were not involved in building this to test through the flows once as an event creator, and again as users purchasing tickets and access an event.
6. When the UX is minimally functional end-to-end, get initial feedback from potential Beta users.
7. [Document the Pagoda managed services](https://docs.google.com/spreadsheets/d/1fSJVEZL_tVW46AmYWsUg2f90ZdwpYY0ZzM81kkJ8v-w/edit?gid=0#gid=0) that support this UX ( e.g. API Proxies for stripe and IPFS, etc)
8. Review with Dustin for a perspective on monetizing the Pagoda managed services and determine potential pricing tiers
9. A security review on the overall UX
10. Document what changes would be needed to ensure that tickets can be scanned while network connectivity is problematic
11. Document the expected limits on scalability (e.g. tickets purchased per min, tickets validated per min, etc)
12. Monitoring & Alerting for key performance indicators
13. Document deployment processes for the app and all supporting services
14. Document where & how nonces are used, and how they might cause failures. 
15. Create a blog for docs.near.org (perhaps on the process of building this app and guidance for developers on how to use the template)
16. Create a marketing blurb for twitter and nearweeknews
17. Additional promotion (DevHub's weekly meeting?)

**Success Metrics**

Weekly

1. Support Ticket Volume: Monitor the number and nature of support tickets raised. A decrease in monthly support tickets can indicate an improvement in user experience and overall UX.

Monthly

1. A month-over-month increase in the number of NFT transactions from Events as a percentage of total NFT transactions on Near.
2. A month-over-month increase in the # of clones of the boilerplate template app
18. A month-over-month increase in the claims of proof-of-attendance NFTs which become accessible to users after their tickets are scanned at the event.
19. Positive feedback on the overall event producer experience and impact on their profitability from event producers.
20. Positive feedback on the overall user experience and ticket pricing from attendees.

Quarterly
1. A quarter-over-quarter increase in Repeat Attendee Rate: Measure the proportion of attendees who return for subsequent events in a given series. This can help gauge the loyalty and satisfaction for a producer’s community.
3. A quarter-over-quarter increase in Producer Onboarding Rate: The rate at which new event producers start using this product. Growth in producer adoption reflects the platform’s value proposition to event organizers.
4. An increase in NFT Ticketing Adoption Rate: For each producer’s event, Track the percentage of tickets issued via this product against the total number of traditional tickets made available on other platforms. An increasing trend can indicate successful platform adoption and acceptance of the overall UX.

```[tasklist]
### Tasks
- [ ] https://github.com/near/pagoda-experiments/issues/1
- [ ] https://github.com/near/pagoda-experiments/issues/2
- [ ] https://github.com/near/pagoda-experiments/issues/3
- [ ] https://github.com/near/pagoda-experiments/issues/4
- [ ] https://github.com/near/pagoda-experiments/issues/5
- [ ] https://github.com/near/pagoda-experiments/issues/6
- [ ] https://github.com/near/pagoda-experiments/issues/7
- [ ] https://github.com/near/pagoda-experiments/issues/8
- [ ] https://github.com/near/pagoda-experiments/issues/9
- [ ] https://github.com/near/pagoda-experiments/issues/10
- [ ] https://github.com/near/pagoda-experiments/issues/11
- [ ] https://github.com/near/pagoda-experiments/issues/12
- [ ] https://github.com/near/pagoda-experiments/issues/13
- [ ] https://github.com/near/pagoda-experiments/issues/14
- [ ] https://github.com/near/pagoda-experiments/issues/15
- [ ] https://github.com/near/pagoda-experiments/issues/17
- [ ] https://github.com/near/pagoda-experiments/issues/20
- [ ] https://github.com/near/pagoda-experiments/issues/18
- [ ] https://github.com/near/pagoda-experiments/issues/16
- [ ] https://github.com/near/near-discovery/issues/1194
- [ ] https://github.com/near/near-discovery/issues/1198
- [ ] https://github.com/near/near-discovery/issues/1253
- [ ] https://github.com/near/near-discovery/issues/1254
- [ ] https://github.com/near/near-discovery/issues/1285
```
