### ISSUE TITLE
🔷 [Epic] near.ai marketing pages

### ISSUE THREAD

**Issue by gabehamilton** [near/near-discovery#1166]
## Near.ai marketing pages

- **High Level Goal:**

```[tasklist]
### Tasks
- [x] near.ai lands users separately from near.org
- [x] A user navigating to near.ai  sees AI blog entries.
- [ ] https://github.com/near/near-discovery/issues/1167
- [ ] There is a near.ai about page.
- [ ] Page that explains the Ideathon
```

Launch before 5/21 communications.

- **UX Designs:**

Use existing repo: https://github.com/near/nearorg_container
Choose a Near accent color for AI.
