### ISSUE TITLE
Add newsletter page to dev.near.org

### ISSUE THREAD

**Issue by gagdiez** [near/near-discovery#1332]
We need to tailor the news page to reflect our newsletter, 

utilizing the mailchimp api 
```[tasklist]
### Tasks
- [x] Add a subscribe form within the newsletter page
- [x] Present the latest issue
- [x] Provide access to previous issues
```

**Comment by thisisjoshford** [comment]
@flmel reach out to @joe and sync on newsletter modifications and detail your plan here please :)

**Comment by flmel** [comment]
closed by #1355
