### ISSUE TITLE
Add DAO as part of the tooling

### ISSUE THREAD

**Issue by gagdiez** [near/near-discovery#1353]
**Background**
Our developer portal makes it easy for developers to create basic primitives such as FTs, NFTs and Linkdrops. We want to continue growing this toolset, by adding DAOs, which is another common blockchain primitive

**Task**
- [ ] Allow users to create a DAO from the `Tools` section
- [ ] List the DAOs created by the user
- [x] Display a link on each DAO to a site where the DAO can be used

**Additional context**
https://github.com/near/near-discovery/pull/1336
