### ISSUE TITLE
🔷 [Epic] Near.org UI Performance Improvements

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#380]
### Problem
UI performance of near.org does not match a typical user's expectations, and is extremely poor with an internet speed below 200 Mbps. 

### Areas for Improvement
* Improve performance when running near.org locally via pnpm dev
* Improve the fetching of components from the VM. Currently, each URL update refreshes the entire UI (must each URL update re-fetch VM component?)
* Improve the Caching of Data fetched by VM components

How might we improve UI performance for each of the above areas?

### Relevant Conversations 
* [Considering Redux w/ Flux architecture](https://github.com/near/near-discovery/pull/240) tl; dr; We could expand our use of Zustand to accomplish the same as redux, however this would not address the source of our rendering bottleneck: loading components from the VM & component data fetching. 
* [Porting more components to QueryAPI](https://github.com/near/near-discovery/issues/313)

```[tasklist]
### Tasks
- [ ] https://github.com/near/near-discovery/issues/673
- [ ] https://github.com/near/near-discovery/issues/693
- [ ] https://github.com/near/near-discovery-components/issues/425
- [ ] https://github.com/near/near-discovery-components/issues/427
- [ ] https://github.com/near/near-discovery/issues/739
- [ ] https://github.com/near/near-discovery-components/issues/446
- [ ] https://github.com/near/near-discovery-components/issues/447
- [ ] https://github.com/near/near-discovery/issues/779
- [ ] https://github.com/near/near-discovery/issues/854
- [ ] https://github.com/near/near-discovery/issues/853
- [ ] https://github.com/near/near-discovery/issues/855
```

**Comment by charleslavon** [comment]
@mpeterdev @marcinbodnar @calebjacob @Patrick1904 @shelegdmitriy would appreciate your feedback on clarifying/adding areas for improvement or proposing potential solutions.

**Comment by calebjacob** [comment]
I think the biggest bottleneck we have right now is the number of HTTP requests when loading any page. If you look at the network inspector when visiting the activity feed, you can see just how insane it is:

<img width="568" alt="Screen Shot 2023-09-08 at 2 28 04 PM" src="https://github.com/near/near-discovery/assets/1475067/b5e01c3a-600d-47cb-ae02-e4e6170bf78a">

It's especially bad for pages that render a list of resources (posts, component cards, etc). I think a lot of this is due to the current limitations and design of the VM, but we should do some further investigating:

- The Next JS app and how we initialize/use the VM
- The VM and how it fetches component code and data

**Comment by charleslavon** [comment]
@calebjacob what are yours thoughts on approaching this initiative by ranking the tickets & areas of potentials UX improvement top down by (lower time/effort & highest impact on perceived performance) to (greater time/effort & high impact on perceived performance) to  (greatest time/effort & good impact on perceived performance).   And working on the lower/cost high impact items first?

**Comment by calebjacob** [comment]
@charleslavon That sounds like a great idea. Our very first task should probably be a time block to come up with those list of tasks and approximate effort.

**Comment by calebjacob** [comment]
Hey @charleslavon, I did a ton of research on how the current VM is handling caching things like `Social.get()` and fetching `Widget` code. It actually does a really good job of caching everything it can and preventing HTTP requests. At this point, I don't see any improvements that need to be made inside the VM - most of these performance issues should be resolvable inside our BOS components with some refactoring.
