### ISSUE TITLE
🔷 [Epic] MVP Moderation

### ISSUE THREAD

**Issue by gabehamilton** [near/near-discovery#382]
## Description
Initial moderation functionality for Discovery 

## Resources

```[tasklist]
### Tasks
- [ ] https://github.com/near/near-discovery/issues/381
- [ ] https://github.com/near/near-discovery/issues/383
- [ ] https://github.com/near/near-discovery-components/issues/315
```
