### ISSUE TITLE
🔷 [Epic] [P0] Reporting Flow

### ISSUE THREAD

**Issue by tidus974** [near/near-discovery#390]
**Old Jira Task: https://pagodaplatform.atlassian.net/browse/ROAD-279**
![image-20230711-102037](https://github.com/near/near-discovery/assets/5955639/e98f4c19-851b-494e-91d5-bf7be2c80afa)
![image-20230711-102054](https://github.com/near/near-discovery/assets/5955639/521137ba-9f8d-4f75-aab6-e36d3b1fa74d)
## Description

Summary: Creating a reporting flow for http://near.org/ , including designing a user interface for tracking reported content, implementing notification systems for users regarding moderator decisions, adding a pop-up confirmation message when content is reported, and considering the inclusion of optional violation options for users when reporting.

## Resources
Product Hypothesis: https://docs.google.com/document/d/1rs1LZld_eZ2_YaCPvH9x8kWrzLxSjDtJJzd2UpzIC-w/edit#heading=h.cvd6d15qyce 

Figma Ideation Session: https://www.figma.com/file/2DLXKTN9kH0zwDQpr1CvHs/Ideation%3A-Reporting?type=whiteboard&node-id=68-233&t=NSoIHbmH9vCK4aRI-0 

```[tasklist]
### NEARCON Tasks
- [ ] https://github.com/near/near-discovery/issues/543
- [ ] https://github.com/near/near-discovery/issues/391
- [ ] https://github.com/near/near-discovery/issues/392
- [ ] https://github.com/near/near-discovery/issues/393
- [ ] https://github.com/near/near-discovery/issues/423
- [ ] https://github.com/near/near-discovery/issues/378
- [ ] https://github.com/near/near-discovery-components/issues/412
- [ ] https://github.com/near/near-discovery-components/issues/415
- [ ] https://github.com/near/near-discovery/issues/422
```

```[tasklist]
### Q4 Tasks
- [ ] https://github.com/near/near-discovery/issues/394
- [ ] https://github.com/near/near-discovery/issues/395
- [ ] https://github.com/near/near-discovery/issues/396
- [ ] https://github.com/near/near-discovery/issues/397
- [ ] https://github.com/near/near-discovery/issues/715
```

```[tasklist]
### Q1-24" Tasks
- [ ] https://github.com/near/near-discovery/issues/399
- [ ] https://github.com/near/near-discovery/issues/398
```

**Comment by xuan-ytr** [comment]
Finalized reporting flow
- [Flow chart](https://www.figma.com/proto/bD7wRz3SLLh0N2EwTFjFEQ/Reporting?page-id=105%3A447&type=design&node-id=130-2327&viewport=718%2C631%2C0.25&t=WpRa5Ot8FHHqXqvO-8&scaling=scale-down-width&hide-ui=1)
- [Raw figma](https://www.figma.com/file/bD7wRz3SLLh0N2EwTFjFEQ/Reporting?type=design&node-id=105%3A447&mode=design&t=zk7M1Abcj8ail7EC-1)
