### ISSUE TITLE
🔷 [Epic] [P1] Enforcement actions implementation

### ISSUE THREAD

**Issue by tidus974** [near/near-discovery#406]
## Description
We will be building enforcement actions for our moderation team who are reviewing content present on the primary socialDB. But also basic actions for users to curate their feed. 

Some of the features we will be creating will live in the [review queue(https://near.org/#/mob.near/widget/Flagged.Feed) ](https://near.org/#/mob.near/widget/Flagged.Feed) and will only be accessible/usable by our moderation team (e.g. “Hide this post“ button near the post). 

Other features will be visible directly on any user’s feed (e.g. Ability to block/hide account).

For each task, we will describe the feature and the figma design.

```[tasklist]
### NEARCON Tasks
- [ ] https://github.com/near/near-discovery/issues/407
- [ ] https://github.com/near/near-discovery/issues/417
- [ ] https://github.com/near/near-discovery/issues/517
- [ ] https://github.com/near/near-discovery-components/issues/375
- [ ] https://github.com/near/near-discovery-components/issues/374
- [ ] https://github.com/near/near-discovery-components/issues/376
- [ ] https://github.com/near/near-discovery-components/issues/414
```

```[tasklist]
### Q4 Tasks
- [ ] https://github.com/near/near-discovery/issues/698
- [ ] https://github.com/near/near-discovery/issues/554
- [ ] https://github.com/near/near-discovery/issues/420
- [ ] https://github.com/near/near-discovery/issues/421
- [ ] https://github.com/near/near-discovery/issues/426
- [ ] https://github.com/near/near-discovery/issues/427
- [ ] https://github.com/near/near-discovery/issues/428
- [ ] https://github.com/near/near-discovery-components/issues/413
```

```[tasklist]
### Q1-24" Tasks
- [ ] https://github.com/near/near-discovery/issues/429
- [ ] https://github.com/near/near-discovery/issues/430
- [ ] https://github.com/near/near-discovery/issues/431
- [ ] https://github.com/near/near-discovery/issues/432
```

**Comment by xuan-ytr** [comment]
WIP mockup for moderation by accounts [here](https://www.figma.com/proto/lU0iymN7JMIcr3c4tom0Lr/Moderation-%2B-Enforcement-Actions?page-id=12%3A11233&type=design&node-id=12-23246&viewport=-790%2C743%2C0.83&t=0awHVyNDWaC5C4pi-1&scaling=min-zoom&mode=design). Current UX / functionality owned by @gabehamilton
