### ISSUE TITLE
🔷 [Epic] Redesigned Static Pages for near.org

### ISSUE THREAD

**Issue by heycorwin** [near/near-discovery#424]
```[tasklist]
### Tasks
- [ ] https://github.com/near/near-discovery/issues/411
- [ ] https://github.com/near/near-discovery/issues/413
- [ ] https://github.com/near/near-discovery/issues/412
- [ ] https://github.com/near/near-discovery/issues/415
- [ ] https://github.com/near/near-discovery/issues/414
```

**Comment by charleslavon** [comment]
@heycorwin I believe these designs are complete. Can this epic be closed?

**Comment by vanessadespain** [comment]
@charleslavon I'm taking the last couple days of this week to button up Home, Learn, and Ecosystem and then will be ready to mark complete. 

Blog and Events were put on hold so they will either remain part of the epic or go back into the backlog until we figure out how the CMS for these pages will work.

**Comment by heycorwin** [comment]
@charleslavon Did you not want to use this Epic + these issues for engineering as well? That was the intent (I imagined engineering would be implementing one page at a time via the issues in the tasklist)

I imagined that the work would just get moved into "Ready for Development" on your project board and an engineer could just create a branch from the issues with the designs attached.

If this isn't how y'all like to work that's totally cool but just for my own sake I'd love to learn more about what your preferences would be so design can accommodate 🙌🏻

**Comment by charleslavon** [comment]
@heycorwin that could work but I see that Caleb has already added implementation tasks directly on the [Initiative](https://github.com/near/Pagoda-Roadmap/issues/22), so looks like we're ok to use this Epic to track the design work.
