### ISSUE TITLE
🔷 [Epic] [P2] Setting up moderation Automation

### ISSUE THREAD

**Issue by tidus974** [near/near-discovery#433]
## Description
General information: https://docs.google.com/document/d/1T1l4LZhO10mMlhVDj-Mg8K8943mLpPgaZtFJBiT0IUg/edit 

## Resources
[(Relevant documentation, Figma links, and other reference material)](https://www.figma.com/file/lkQJTFMe8KeMb4ghvX5GqI/Ideation%3A-Automation?type=whiteboard&node-id=324-884&t=2yzVJFmSh5OUjjI4-0)

![image-20230801-101908](https://github.com/near/near-discovery/assets/5955639/e78ed2a1-5cd6-4eea-ad5c-9a1979f9e1b7)
![image-20230801-101913](https://github.com/near/near-discovery/assets/5955639/4efd0711-1e1c-4e4e-972c-1aff26e620c4)
![image-20230801-101900](https://github.com/near/near-discovery/assets/5955639/2e4eefb2-085f-4f75-a0de-8b050acdd9aa)

```[tasklist]
### Q4 Tasks
- [ ] https://github.com/near/near-discovery/issues/434
- [ ] https://github.com/near/near-discovery/issues/436
- [ ] https://github.com/near/near-discovery/issues/437
- [ ] https://github.com/near/near-discovery/issues/438
- [ ] https://github.com/near/near-discovery/issues/440
- [ ] https://github.com/near/near-discovery/issues/443
- [ ] https://github.com/near/near-discovery/issues/444
- [ ] https://github.com/near/near-discovery/issues/445
- [ ] https://github.com/near/near-discovery/issues/447
- [ ] https://github.com/near/near-discovery/issues/448
```

```[tasklist]
### Q1-24" Tasks
- [ ] https://github.com/near/near-discovery/issues/439
- [ ] https://github.com/near/near-discovery/issues/441
- [ ] https://github.com/near/near-discovery/issues/442
- [ ] https://github.com/near/near-discovery/issues/446
- [ ] https://github.com/near/near-discovery/issues/449
- [ ] https://github.com/near/near-discovery/issues/450
- [ ] https://github.com/near/near-discovery/issues/451
- [ ] https://github.com/near/near-discovery/issues/452
```

**Comment by tidus974** [comment]
Backlogged as discussed here https://docs.google.com/document/d/1jNw0qFMLzi_3xKLmKZDEINxY8omzXF5VedcXCeHh7aQ/edit
