### ISSUE TITLE
🔷 [Epic] [P3] Customized Content Preferences

### ISSUE THREAD

**Issue by tidus974** [near/near-discovery#453]
## Description
Product Hypothesis:https://docs.google.com/document/d/1mBV8FwBdRjKmRb_w-Rvp1dK_t1a4S_-y8hGDzGpoRqA/edit 
Figma Ideation: https://www.figma.com/file/V5Dn9ck0akUKL6nnjFvg8b/Ideation%3A-Customized-Content-Preferences?type=whiteboard&node-id=2-600&t=Zk7TUiZvwctw8TpM-0 

MVP: From P0 to P5

Related to private data, consider https://fractal.notion.site/IDOS-MVP-for-NEAR-558da023a49e4043a44cb22395654bbd 

Summary: Empower http://near.org/  users with customized content preferences based on age, topics and other account preferences while respecting local regulations. By providing users control over their content experience, we aim to uphold freedom of expression while promoting a safer and more personalized social media environment.

```[tasklist]
### NEARCON Tasks
- [ ] https://github.com/near/near-discovery/issues/464
```

```[tasklist]
### Q4 Tasks
- [ ] https://github.com/near/near-discovery/issues/454
- [ ] https://github.com/near/near-discovery/issues/455
- [ ] https://github.com/near/near-discovery/issues/456
- [ ] https://github.com/near/near-discovery/issues/457
- [ ] https://github.com/near/near-discovery/issues/458
- [ ] https://github.com/near/near-discovery/issues/459
- [ ] https://github.com/near/near-discovery/issues/467
- [ ] https://github.com/near/near-discovery/issues/460
- [ ] https://github.com/near/near-discovery/issues/461
- [ ] https://github.com/near/near-discovery/issues/462
```

```[tasklist]
### Q1-24" Tasks
- [ ] https://github.com/near/near-discovery/issues/463
- [ ] https://github.com/near/near-discovery/issues/465
- [ ] https://github.com/near/near-discovery/issues/466
- [ ] https://github.com/near/near-discovery/issues/468
```
