### ISSUE TITLE
P11 [NEARCON] Verified account. Show overlays or some visual of how "verified/legit" content is based on review, usage, poster, etc.

### ISSUE THREAD

**Issue by tidus974** [near/near-discovery#464]
```[tasklist]
### Tasks
- [ ] https://github.com/near/near-discovery/issues/381
- [ ] https://github.com/near/near-discovery-components/issues/352
- [ ] https://github.com/near/near-discovery-components/issues/353
```
