### ISSUE TITLE
🔷 [Epic] [P4] Volunteer Moderation

### ISSUE THREAD

**Issue by tidus974** [near/near-discovery#469]
Top Documents:
[Product Hypothesis One-Pager - Community Moderation (WIP)](https://docs.google.com/document/d/1FW4kHgwqNx-xLh-kxjyMQcft9z9f54PwJ8vUaZ5q6zo/edit#heading=h.cvd6d15qyce) 

[Ideation: Community Moderation](https://www.figma.com/file/FCfRoO38aulxJ4rOTEjGyM/Ideation%3A-Community-Moderation?type=whiteboard&node-id=330-237&t=BqwPMHf8EqDR1L4o-0)
```[tasklist]
### Q4 Tasks
- [ ] https://github.com/near/near-discovery/issues/470
- [ ] https://github.com/near/near-discovery/issues/471
- [ ] https://github.com/near/near-discovery/issues/472
- [ ] https://github.com/near/near-discovery/issues/473
- [ ] https://github.com/near/near-discovery/issues/474
- [ ] https://github.com/near/near-discovery/issues/475
- [ ] https://github.com/near/near-discovery/issues/476
- [ ] https://github.com/near/near-discovery/issues/477
```

```[tasklist]
### Q1-24" Tasks
- [ ] https://github.com/near/near-discovery/issues/498
- [ ] https://github.com/near/near-discovery/issues/497
- [ ] https://github.com/near/near-discovery/issues/478
- [ ] https://github.com/near/near-discovery/issues/479
- [x] https://github.com/near/near-discovery/issues/480
- [x] https://github.com/near/near-discovery/issues/481
- [ ] https://github.com/near/near-discovery/issues/482
- [ ] https://github.com/near/near-discovery/issues/483
- [ ] https://github.com/near/near-discovery/issues/484
- [ ] https://github.com/near/near-discovery/issues/485
- [ ] https://github.com/near/near-discovery/issues/486
- [ ] https://github.com/near/near-discovery/issues/487
- [ ] https://github.com/near/near-discovery/issues/488
- [ ] https://github.com/near/near-discovery/issues/489
- [ ] https://github.com/near/near-discovery/issues/490
- [ ] https://github.com/near/near-discovery/issues/491
- [ ] https://github.com/near/near-discovery/issues/492
- [ ] https://github.com/near/near-discovery/issues/493
- [ ] https://github.com/near/near-discovery/issues/494
- [ ] https://github.com/near/near-discovery/issues/495
- [ ] https://github.com/near/near-discovery/issues/496
```

**Comment by tidus974** [comment]
Backlogged as discussed here https://docs.google.com/document/d/1jNw0qFMLzi_3xKLmKZDEINxY8omzXF5VedcXCeHh7aQ/edit
