### ISSUE TITLE
🔷 [Epic] [P5] Data Reporting and Investigation

### ISSUE THREAD

**Issue by tidus974** [near/near-discovery#499]
## Description
To ensure the efficacy and efficiency of our content moderation efforts, we aim to establish robust data reporting and investigation mechanisms. These mechanisms will not only track the performance of the moderation system but also provide insights into areas of improvement, trends in violations, and user feedback. This will facilitate informed decision-making and aid in continually refining our content moderation strategies.

```[tasklist]
### Q1-24" Tasks
- [ ] https://github.com/near/near-discovery/issues/500
- [ ] https://github.com/near/near-discovery/issues/501
- [ ] https://github.com/near/near-discovery/issues/503
- [ ] https://github.com/near/near-discovery/issues/504
- [ ] https://github.com/near/near-discovery/issues/505
- [ ] https://github.com/near/near-discovery/issues/506
- [ ] https://github.com/near/near-discovery/issues/507
```
