### ISSUE TITLE
Give moderator the ability to ban a specific post or comment.

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#517]
```[tasklist]
### Tasks
- [x] New moderation widget
- [x] Moderate account in new data format
- [x] Moderate post in new data format
- [ ] Moderate comment in new data format
```
