### ISSUE TITLE
🔷 [Epic] P0 Document Management

### ISSUE THREAD

**Issue by tidus974** [near/near-discovery#518]
Work between Legal POC and Product team. All details are recorded here: https://docs.google.com/document/d/1iOY_eb_FZneJaP-IqXPXqFUaRuQOXukGLXE-ZkvGZs4/edit#
```[tasklist]
### NEARCON Tasks
- [ ] https://github.com/near/near-discovery/issues/526
- [ ] https://github.com/near/near-discovery/issues/553
- [ ] https://github.com/near/near-discovery/issues/525
- [ ] https://github.com/near/near-discovery/issues/522
- [ ] https://github.com/near/near-discovery/issues/523
- [ ] https://github.com/near/near-discovery/issues/524
```
