### ISSUE TITLE
🔷 [Epic] MVP Notifications Fast Follows (Settings, UI Improvements, etc)

### ISSUE THREAD

**Issue by ravigautham** [near/near-discovery#537]
## Description
(Overview of milestone or function governed by this epic)

## Resources
(Relevant documentation, Figma links, and other reference material)

1. Item 1
1. Item 2
1. Item 3

```[tasklist]
### Tasks
- [ ] https://github.com/near/near-discovery/issues/574
- [ ] https://github.com/near/near-discovery/issues/570
- [ ] https://github.com/near/near-discovery/issues/572
- [ ] https://github.com/near/near-discovery/issues/575
- [ ] https://github.com/near/near-discovery/issues/645
- [ ] https://github.com/near/near-discovery/issues/662
- [ ] https://github.com/near/near-discovery/issues/583
- [ ] https://github.com/near/near-discovery/issues/627
- [x] Click Area on Notification should take user to relevant content instead of profile #584
- [ ] https://github.com/near/near-discovery/issues/776
- [ ] https://github.com/near/near-discovery/issues/775
```
