### ISSUE TITLE
🔷 [Epic] P1 Integrating Fractal's idOS solution to Near.org

### ISSUE THREAD

**Issue by tidus974** [near/near-discovery#555]
## Description
Integrating Identity and Private Data management into near.org

**Here is what we've defined as the scope of work to consider all product work completed:** 

Provide the ability to verify your account via idOS using [near.org](http://near.org/) setting page and showcase verification badge, which entails:
        - UI "Identity & Data Privacy" page creation
        - UI - Show badges at account page
        - idOS <-> [Near.org](http://near.org/) data integration
        - ability to redirect to idOS service for verification
        - Get verification details at setting page
        - Showcase verification badge throughout [near.org](http://near.org/)

[Figma link](https://www.figma.com/proto/dmfi3WIjvfyoXBVaPdqRvt/IDOS-integration?page-id=153%3A8850&type=design&node-id=341-5425&viewport=661%2C583%2C0.06&t=NJa0hmKQ0s5vGMLG-8&scaling=scale-down-width&starting-point-node-id=244%3A36117&hide-ui=1)

This epic consists of integrating [Fractal's idOS SDK](https://github.com/idos-network/idos-sdk-js) into near.org as needed to [realize these designs](https://www.figma.com/proto/dmfi3WIjvfyoXBVaPdqRvt/IDOS?page-id=153%3A8850&type=design&node-id=244-36117&viewport=1082%2C605%2C0.07&t=RQHSG3DM8TCjwvyq-1&scaling=scale-down-width&starting-point-node-id=244%3A36117)

```[tasklist]
### NEARCON Tasks
- [ ] https://github.com/near/near-discovery/issues/556
- [ ] https://github.com/near/near-discovery/issues/636
- [ ] https://github.com/near/fast-auth-signer/issues/67#issuecomment-1739754647
- [x] Share, Edit, Delete, Show actions to manage Saved Credentials [Fractal]
```

**Comment by xuan-ytr** [comment]
@shelegdmitriy @charleslavon descoped [spec prototype here](https://www.figma.com/proto/dmfi3WIjvfyoXBVaPdqRvt/IDOS?page-id=153%3A8850&type=design&node-id=153-9514&viewport=2886%2C2560%2C0.5&t=d2v6ijRxfYQAFwCj-8&scaling=scale-down-width&starting-point-node-id=244%3A36117&hide-ui=1), ready for implementation.
