### ISSUE TITLE
🔷 [Epic] Notifications Unscheduled Enhancements

### ISSUE THREAD

**Issue by ravigautham** [near/near-discovery#621]
## Description

This epic captures improvements to the UI experience within the notification tab on near.org as well other related enhancements to the notification experience.

## Resources
(Relevant documentation, Figma links, and other reference material)

```[tasklist]
### Tasks
- [ ] https://github.com/near/near-discovery/issues/599
- [ ] https://github.com/near/near-discovery/issues/658
- [ ] https://github.com/near/near-discovery/issues/668
- [ ] https://github.com/near/near-discovery/issues/573
- [ ] https://github.com/near/near-discovery/issues/547
- [ ] https://github.com/near/near-discovery/issues/572
- [ ] https://github.com/near/near-discovery/issues/570
```

**Comment by ravigautham** [comment]
@charleslavon Where can I view the start/target dates for epics?

**Comment by ravigautham** [comment]
@charleslavon I've updated this epic to reflect the tasks that would capture the UI improvements needed for the notification tab.
