### ISSUE TITLE
Enable tracking of forked components

### ISSUE THREAD

**Issue by thisisjoshford** [near/near-discovery#622]
### Description
Create the ability to track forked components similar to GitHub's existing functionality. 

A fork should be defined as when an existing component (with or without modifications) has been **published on-chain** by an accountId that differs from the original author. We should also take into consideration how forks of forks will be tracked.

---

### Goal
Implementation:
- [x] https://github.com/near/near-discovery/issues/341
  
Design:
- [ ] Display # of forks a component has
- [ ] Display # of forks a user has 
---

### Resources
- https://github.com/near/data-platform/issues/2
- [Component Profile Page Design ](https://www.figma.com/file/tWVSAyZKWDzFyyGTI1jFAr/Component-Discovery?type=design&node-id=912-922&mode=design&t=gKBv3HL3r4KudUKR-4)

**Comment by charleslavon** [comment]
@thisisjoshford @heycorwin We've suggested an implementation approach [here](https://github.com/near/near-discovery/issues/341)
