### ISSUE TITLE
P1 Settings management UI, limited to showing the Identity & data privacy section [Pagoda]

### ISSUE THREAD

**Issue by tidus974** [near/near-discovery#636]
```[tasklist]
### Tasks
- [ ] Create a base layout with tabs and content
- [ ] https://github.com/near/near-discovery/issues/644
- [ ] https://github.com/near/near-discovery/issues/647
- [x] Create NEARCON Use Case Figma presentation [Design]
```
