### ISSUE TITLE
🔷 [Epic] Groups Implementation

### ISSUE THREAD

**Issue by charleslavon** [near/near-discovery#678]
## Description
Scope, task breakdown & target milestone(s) to be added by lead developers

[Social Enhancement Proposal ](https://github.com/NearSocial/SEPs/pull/2)  
```[tasklist]
### Tasks
- [ ] https://github.com/near/near-discovery/issues/844
- [ ] https://github.com/near/near-discovery/issues/845
- [ ] https://github.com/near/near-discovery/issues/846
- [ ] https://github.com/near/near-discovery/issues/847
- [ ] https://github.com/near/near-discovery/issues/848
- [ ] https://github.com/near/near-discovery/issues/849
- [ ] https://github.com/near/near-discovery/issues/880
- [ ] https://github.com/near/near-discovery/issues/881
```
