### ISSUE TITLE
Enable tracking of favorited components

### ISSUE THREAD

**Issue by thisisjoshford** [near/near-discovery#692]
### Description
Developers should be able to save (e.g. 'star') components that they find useful for later reference. Additionally, components should track and display how often they have been starred to help indicate their usefulness.

---

### Goal
- [ ] Create a new [user profile page](https://www.figma.com/file/eIN40ZtBHDlLMB1LXCK5Jn/Developer-Profiles?type=design&node-id=1-8469&mode=dev)
- [ ] Components starred by users are displayed on the `Stars` tab of a user's profile page
- [ ] Update the Component Details Page to display a count of `Stars` next to the fork button under the Component's name (the designs show this as 'Likes' but let's go with stars for now)
- [ ] @gabehamilton How might we resolve our goals here to be compatible with the Stars implementation that Eugene recently shipped?
> https://github.com/NearSocial/viewer/pull/207
[Star Button component](https://near.org/near/widget/ComponentDetailsPage?src=mob.near/widget/N.StarButton&tab=source)
<img width="543" alt="Screen Shot 2023-11-03 at 8 49 28 AM" src="https://github.com/near/near-discovery/assets/1915116/07790dbc-9251-4ff4-b615-129a4d382745">

---

### Resources

- [Star Button component](https://near.org/near/widget/ComponentDetailsPage?src=mob.near/widget/N.StarButton&tab=source)

- https://github.com/NearSocial/viewer/pull/207

**Comment by thisisjoshford** [comment]
> @thisisjoshford can you think of any reason we shouldn't just change favorites to stars and treat these just like Github?

Nope, sounds good to me :)

**Comment by heycorwin** [comment]
This is now reflected in the new design spec for the developer profiles:

https://www.figma.com/file/eIN40ZtBHDlLMB1LXCK5Jn/Developer-Profiles?type=design&node-id=1-8469&mode=dev

**Comment by thisisjoshford** [comment]
@evgenykuzyakov just shipped staring of components on near.social gateway ❤️ 

- https://github.com/NearSocial/viewer/pull/207
- [Star Button component](https://near.org/near/widget/ComponentDetailsPage?src=mob.near/widget/N.StarButton&tab=source)

**Comment by charleslavon** [comment]
@calebjacob @gabehamilton consider this task for next week's sprint.

**Comment by calebjacob** [comment]
I'm happy to collaborate with @gabehamilton on this. I can implement the frontend - I'll just need some help thinking through how the star action and data should be tracked.

Also, @thisisjoshford can we descope this component from the ticket and implement it separately?

<img width="432" alt="Screen Shot 2023-11-03 at 10 05 20 AM" src="https://github.com/near/near-discovery/assets/1475067/19efc856-1cda-4aa6-a947-56d5bb75c69c">

I'm not sure we have all the data we need to achieve it right now. This component alone will be a decent amount of effort compared to the rest of this ticket.

**Comment by calebjacob** [comment]
Whoops, just realized it was already broken out: https://github.com/near/near-discovery/issues/623

Still drinking my coffee :)
