### ISSUE TITLE
🔷 [Epic] Blog

### ISSUE THREAD

**Issue by ilblackdragon** [near/near-discovery#943]
## What ?

- **High Level Goal:**

Transition [near.org/blog](https://near.org/blog) from wordpress embed to NearJS component based blog, where each blog is a socialDB Post, and allow designated accounts (curators) to easily promote blog posts written by any contributors in the ecosystem.

- **UX Designs:**

  - [Working Figma File](https://www.figma.com/file/nqgzMvVASTSHVqUQPFQWsV/WORKING-%2F-Q1-'24-%2F-Website---v3.2024?type=design&node-id=0%3A1&mode=design&t=mHQGDDKFmgFcgmXJ-1)
  - Dev Ready Designs [TBD]

---

## Why ?

- **Background:**

Current embed has a number of limitations:
 - Broken SEO: content is hosted on another domain, and search frequently bypasses near.org
 - Impossible to measure traffic: users leave near.org if they click on any link
 - No engagement: even if users want to ask questions or engage with comment, there is no way to do that

- **Move the Needle:**

 1. More page visits for near.org from traffic that is going to page.near.org right now
 2. More signups due to engagement with comments
 3. More blog content because curators can promote posts from any author vs required access to wordpress 
 4. As a logged in user, I'm going to receive push notifications about new posts

---

## How ?

```[tasklist]
### Required in order to deprecate wordpress
- [ ] Any socialDB user can create blog posts on the socialDB `main` feed
- [ ] Only blog posts posted or reposted by SocialDB accounts designated as curators should be featured on the near.org/blog feed.
- [ ] Perhaps we manage curators similar to [how content moderators are coded ](https://github.com/near/near-discovery-components/blob/10e8d5420535f511daa3aaecc0a7630a0680fffa/indexers/moderation/moderation.js#L173).
- [ ] should the near.org/blog feed should read posts of type blog from socialDB's `post.main` of type `blog` or perhaps `post.blog` with its own types `feed_display`, `full_display` etc ?
- [ ] one should be able to search for blog posts by the blog title title and author
- [ ] one should be able to sort blogs by most recent, and oldest to newest
- [ ] one should be able to filter blogs by author
- [ ] As a wallet-disconnected reader, after clicking like or entering a comment I'm taken into the  Signup/Login flow which I end up creating account or connecting an existing wallet, and the comment/like gets submitted after the redirect back from wallet connection.
- [ ] A blog post should include a share icon that copies a shortened blog post URL to the clipboard.
- [ ] On the main social feed, and the on the social feed on one's profile page, the post creation input field should facilitate creating a post of type blog.
- [ ] There should be no broken links for legacy blog posts. The [static HTML of legacy blog posts](https://github.com/near/nearorg_marketing/tree/main/public/blog) can be a git submodule and served from near-discovery.
```

```[tasklist]
### Nice to Have Requirements
- [ ] A blog page should provide an affordance allowing one to "repost" the blog with comment. Similar to a quote retweet.
- [ ] A blog page should provide an affordance allowing one to create their own blog post.
- [ ] How might we support filtering by Categories like: Case Studies, Community, Developers, Events, Near Foundation ?
- [ ] How might we support searching blogs by their included hashtags?
- [ ] A blog post should include related posts on a similar topic
- [ ] one should be able to like or comment on a blog post
```

```[tasklist]
### Design Tasks
- [x] Team aligns on UX flows and features for Blog Landing page and posts
- [ ] Define dependencies for Events as a type of blog post
- [x] Design Post "Blog Type" UI/UX flow
- [x] Design Moderator's "Post to Blog" UI/UX
- [ ] Design Edit Blog Post UX
- [x] Create dev-ready designs for Blog Post template
- [x] Create dev-ready designs for Blog Landing page
```

**Comment by gabehamilton** [comment]
To support usability for users who are regularly posting:

To that Required list I would add
 * A User can publish an Edit to any of their blog posts

To the Nice to Have 
  * A draft blog post can be persisted in local storage
  * A user can have multiple draft blog posts
we may also need 
  * for SEO, blog posts can be addressed by a URL that corresponds to the post name

**Comment by ailisp** [comment]
We (DevHub team) also want to reuse the blog component proposed here. Besides the feature proposed here, It would be great if you can support:
- User can delete his blog post
- An optional subtitle for a blog post, for example:
<img width="1323" alt="image" src="https://github.com/near/near-discovery/assets/13259400/58f1dc05-57a2-43e2-abec-9c0cb98609a5">
