### ISSUE TITLE
🔷 [Epic] FounderHub MVP

### ISSUE THREAD

**Issue by LCCCunningham** [near/near-discovery#964]
**MVP**

As a Web3 founder, I need to be able to access tools and resources to help me build my product, identify potential funding opportunities and run a successful business. Today, there are many existing resources, but they are not easily discoverable or well-organized. 

**Vision**
FounderHub is a one-stop shop for Founders building with the near ecosystem. It houses tools and resources that Founders need in order to accelerate their technical product development, start and scale their company, find and participate in relevant community groups, identify resources to build their team, and find funding opportunities.

**Audience**
Primary:
Early stage (pre-seed and seed stage) founders who are building in Web3
Do NOT need to be near native 
Technical and non-technical
Secondary:
Builders who are exploring building a product and starting a business 

**MVP Scope & Requirements**

FounderHub Landing Page
- This landing page will replace the current Horizon [landing page](https://near.org/horizon) on near.org which can be found under the Ecosystem → Founders top navigation menu
- As a founder, I need resources to be intuitively organized on the FounderHub landing page 

MVP Landing Page resources

_Self-Serve resources_

- Content Repository
As a founder, I need to be able to access a repository housing templates, guides and resources essential for my journey.
For the MVP, this Content Repository will be a link to a Notion site- [here](https://near-horizon.notion.site/NEAR-Founder-Hub-Content-Database-d69fcf11613443128fa249fe9fa069f0)

- Founder Co-Pilot
As a founder, I need interactive technical and business support to answer specific questions as I am building my product and company. 
Link to live [version](https://near-cp-alpha.vercel.app/)

- Token Launch Resources
As a founder, I need support in understanding how to launch a token.
Token Launch [Checklist](https://drive.google.com/file/d/117QDZDNE5Dc1EEoIAA7Wf2PiLdNxiBH3/view)

_Ecosystem Community Resources_

- HZN Accelerator Application
As a founder, I need to understand what the HZN Accelerator program is, its core value propositions, who the target audience is, and how to apply.
Link to the application is [here](https://www.hzn.xyz/hzn). Note - we would like to make hzn.xyz the landing page for the HZN application and to sunset / remove front end access to the Horizon marketplace given it is not being actively maintained and there are other products that are solving for the same value props. 

- Funding Opportunities & Founder & Builder Communities
As a founder, I need to understand which funding opportunities exist to support me and which communities I might be able to join. 
Here is an updated [list](https://docs.google.com/document/d/12DkxQddpZmtDAMWyD89igZPL141Z2x9-iOER2jCDyXc/edit#heading=h.g1c5xapiejrw) of these opportunities

- Founder Events
As a founder, I want to be able to access founder-focused events
Link to Founder Success [events](https://lu.ma/u/usr-5oZHY9dEDbDcaHY)

_Feedback + Support area_ 
As a founder, I should be able to provide feedback and ask for further support. I can currently do that via the bottom right hand ? button, which pops up a form. I should be able to use the same form and experience on the FounderHub. All feedback and support requests should be sent to Rei Okamoto's support team. 

**Measuring Success**

Hypotheses to validate / measure

- Validate demand and potential for PMF of a scalable, self-service founder support model 

- Assess demand for specific support offerings / content

- Reach a broader audience + see if there is potential for PLG (e.g. do founders share this with other founders?) 

Proposed initial launch target

- Attract 100+ current near ecosystem founders and builders who use 2+ resources within a month of launch 

**Suggested Release Milestones**
Given this is an MVP and creating a one-stop landing page for resources that already exist, I recommend releasing all the features at once as a GA release. Additionally, we will need a decent amount of volume/traffic to validate / invalidate the offering so a larger immediate audience will help us with the pace of learning and feedback loops.

**GTM** 
In our initial GTM, we will focus on meeting the needs of existing ecosystem founders and builders. Therefore, our distribution tactics will be through grassroots communities (ecosystem DAOs, Discord/TG channels and regional hubs) and we recommend having the protocol twitter handle release a post about its availability. 

The core value propositions / messaging should be focused on highlighting specific resources that are available
Funding opportunities
Token launch resources
Founder co-pilot

In coming months, as we continue to recruit for the HZN cohort, we will promote FounderHub as part of our acquisition strategy with the goal of expanding the number of new Founders who decide to build within the near ecosystem.
```[tasklist]
### Tasks
- [ ] https://github.com/near/near-discovery/issues/974
- [ ] https://github.com/near/near-discovery/issues/975
- [ ] https://github.com/near/near-discovery/issues/976
- [ ] https://github.com/near/near-discovery/issues/977
- [ ] https://github.com/near/near-discovery/issues/999
```

**Comment by thisisjoshford** [comment]
@LCCCunningham should we deprecate https://github.com/near/near-discovery/issues/935 in favor of this issue?

**Comment by LCCCunningham** [comment]
@thisisjoshford - yeah I think that makes sense. Thanks!

**Comment by thisisjoshford** [comment]
Can you migrate anything from #935 to this issue's description? Also drop a comment here and tag @shelegdmitriy when you have the link for the Content Repository Notion site.

**Comment by LCCCunningham** [comment]
Updated with the link to the content rep notion site @shelegdmitriy @thisisjoshford 

Don't need to migrate anything from #935 - thanks!

**Comment by charleslavon** [comment]
@LCCCunningham do you expect that `/horizon` will now redirect to `/founders`? Or should `/horizon` continue to show its current UI?

**Comment by charleslavon** [comment]
@LCCCunningham please provide the token checklist PDF. The link provided is broken

**Comment by shelegdmitriy** [comment]
Overall, this task could be marked as done because the new page is in production already. There is no token checklist PDF file which means missed link to that resource.

cc @charleslavon @LCCCunningham @thisisjoshford

**Comment by LCCCunningham** [comment]
Hey @charleslavon and @shelegdmitriy  - thanks so much for the work on this! Looking great! I updated the ticket description with a new link to the correct token launch checklist. Please lmk if you can access that.

**Comment by LCCCunningham** [comment]
Two additional small issues:

The sub-caption text in the Funding Opportunities box needs to be updated -- it references NEAR Horizon, but this is just about funding ops from the ecosystem. Recommend something like "Explore ecosystem funding opportunities and builder communities to find the right support for your project."

Please update "Self-Serve resources" to "Self-Serve Resources"

**Comment by shelegdmitriy** [comment]
Thanks you @LCCCunningham! That changes are already merged and will be promoted into prod tomorrow (our regular update). Let me know if this needs to be promoted today.

cc @charleslavon

**Comment by LCCCunningham** [comment]
Great @shelegdmitriy - tomorrow is totally fine!

**Comment by shelegdmitriy** [comment]
All this changes are in production already!

cc @LCCCunningham
