### ISSUE TITLE
Create `/papers` landing page

### ISSUE THREAD

**Issue by thisisjoshford** [near/near-discovery#968]
## Issue:
- The [formatting of white papers on `near.org`](https://near.org/papers/the-official-near-white-paper) is not user-friendly and should be resolved.
  - Clicking left nav is clunky and opens a new tab w/ each click
  - Linking from `near.org` -> `docs.near.org` -> `pages.near.org` is suboptimal and not the best UX

## Solution:
Create a landing page for NEAR's technical papers on `near.org/papers` with links to user-friendly PDFs that can be viewed or downloaded.

```[tasklist]
### Tasks
- [ ] Locate original PDF versions of White Paper, Nightshade, & Doomslug. (Convert to PDF if need be)
- [ ] Create a landing page at `near.org/papers` that links to the above papers
- [ ] All papers can be viewed as an interactive PDF or downloadable
- [ ] All papers should have a pathway of `near.org/papers/<paper-title>`
```

## Resources:  
- [ Current papers landing page in docs](https://docs.near.org/concepts/advanced/papers)
- [ Example paper on `pages.near.org`](https://near.org/papers/the-official-near-white-paper)
- [Doomslug.pdf](https://github.com/near/near-discovery/files/14283776/Doomslug.1.pdf)
- [Nightshade.pdf](https://github.com/near/near-discovery/files/14283777/Nightshade.pdf)
- [White Paper NEAR Protocol.pdf](https://github.com/near/near-discovery/files/14283778/White.Paper.NEAR.Protocol.pdf)

**Comment by charleslavon** [comment]
The HTML versions of all papers [are here](https://github.com/near/nearorg_marketing/tree/8a427550c9a8ae4ccdcb94845f7256318f74ba85/public/papers). Perhaps we can apply minimal styles and then convert to PDF via an online converter

**Comment by thisisjoshford** [comment]
[Doomslug (1).pdf](https://github.com/near/near-discovery/files/14283776/Doomslug.1.pdf)
[Nightshade.pdf](https://github.com/near/near-discovery/files/14283777/Nightshade.pdf)
[White Paper NEAR Protocol.pdf](https://github.com/near/near-discovery/files/14283778/White.Paper.NEAR.Protocol.pdf)

**Comment by thisisjoshford** [comment]
@ravigautham @nearlyalmonds this has been prioritized and in development :)

**Comment by ravigautham** [comment]
Thanks @thisisjoshford !
